// Navigation
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const REPLACE_ROUTE = 'REPLACE_ROUTE';
export const RESET_ROUTES = 'RESET_ROUTES';

// Drawer
export const NEW_POUCHDB = 'NEW_POUCHDB';
export const RESET_POUCHDB = 'RESET_POUCHDB';
export const NEW_DRAWER = 'NEW_DRAWER';

// Category Form
export const SET_CATEGORY_TITLE = 'SET_CATEGORY_TITLE';
export const SET_CATEGORY_COLOR = 'SET_CATEGORY_COLOR';
export const SET_CATEGORY_ICON = 'SET_CATEGORY_ICON';
export const OPEN_COLOR_PICKER = 'OPEN_COLOR_PICKER';
export const CLOSE_COLOR_PICKER = 'CLOSE_COLOR_PICKER';
export const OPEN_ICON_PICKER = 'OPEN_ICON_PICKER';
export const CLOSE_ICON_PICKER = 'CLOSE_ICON_PICKER';
export const SET_OFFSET = 'SET_OFFSET';
export const RESET_ADD_CATEGORY_FORM = 'RESET_ADD_CATEGORY_FORM';
export const NEW_CATEGORY = 'NEW_CATEGORY';

// Item Form
export const SET_ITEM_NAME = 'SET_ITEM_NAME';
export const SET_ITEM_CATEGORY = 'SET_ITEM_CATEGORY';
export const RESET_ADD_ITEM_FORM = 'RESET_ADD_ITEM_FORM';
export const NEW_ITEM = 'NEW_ITEM';

// EBudgie
export const LOAD_EBUDGIE = 'LOAD_EBUDGIE';
export const UPDATE_REV = 'UPDATE_REV';
export const RESET_EBUDGIE = 'RESET_EBUDGIE';

// Edit Salary
export const SET_SALARY_VALUE = 'SET_SALARY_VALUE';
export const RESET_EDIT_SALARY_FORM = 'RESET_EDIT_SALARY_FORM';
export const EDIT_SALARY = 'EDIT_SALARY';

// Income Form
export const SET_INCOME_VALUE = 'SET_INCOME_VALUE';
export const SET_INCOME_CATEGORY = 'SET_INCOME_CATEGORY';
export const SET_INCOME_ITEM = 'SET_INCOME_ITEM';
export const RESET_ADD_INCOME_FORM = 'RESET_ADD_INCOME_FORM';
export const SET_INCOME_DATE = 'SET_INCOME_DATE';
export const NEW_INCOME = 'NEW_INCOME';

// Income Form
export const SET_EXPENSE_VALUE = 'SET_EXPENSE_VALUE';
export const SET_EXPENSE_CATEGORY = 'SET_EXPENSE_CATEGORY';
export const SET_EXPENSE_ITEM = 'SET_EXPENSE_ITEM';
export const RESET_ADD_EXPENSE_FORM = 'RESET_ADD_EXPENSE_FORM';
export const SET_EXPENSE_DATE = 'SET_EXPENSE_DATE';
export const NEW_EXPENSE = 'NEW_EXPENSE';

// Settings
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CURRENCY = 'SET_CURRENCY';
export const TOGGLE_PUSH_NOTIFICATIONS = 'TOGGLE_PUSH_NOTIFICATIONS';

// Calendar
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE';
export const NEW_CALENDAR = 'NEW_CALENDAR';

// Detailed Report
export const SET_DETAILED_REPORT_RANGE = 'SET_DETAILED_REPORT_RANGE';

// Report Form
export const SET_REPORT_FORM_DECIMAL_SEPARATOR = 'SET_REPORT_FORM_DECIMAL_SEPARATOR';
export const SET_REPORT_FORM_DELIMITER_CHARACTER = 'SET_REPORT_FORM_DELIMITER_CHARACTER';
export const SET_REPORT_FORM_FROM_DATE = 'SET_REPORT_FORM_FROM_DATE';
export const SET_REPORT_FORM_TO_DATE = 'SET_REPORT_FORM_TO_DATE';
export const TOGGLE_REPORT_FORM_ALL_EVENTS = 'TOGGLE_REPORT_FORM_ALL_EVENTS';
export const RESET_REPORT_FORM = 'RESET_REPORT_FORM';
export const NEW_REPORT_FORM = 'NEW_REPORT_FORM';
